databases:
  - name: annakut-items-planner-db
    plan: free
    region: singapore
    postgresMajorVersion: "16"

services:
  - type: web
    name: annakut-items-planner-backend
    runtime: docker
    repo: https://github.com/maharshichavda-creator/annakut-items-planner
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: annakut-items-planner-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: annakut-items-planner-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: annakut-items-planner-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: annakut-items-planner-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: annakut-items-planner-db
          property: password
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_CORS_ORIGINS
        value: https://annakut-items-planner.onrender.com

  - type: web
    name: annakut-items-planner-frontend
    runtime: static
    repo: https://github.com/maharshichavda-creator/annakut-items-planner
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist/frontend/browser
    plan: free
    region: singapore
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
